FROM node:lts-alpine AS builder
WORKDIR /app
COPY ./openapi .
RUN rm -rf node_modules/ package-lock.json yarn.lock
RUN apk add git
RUN corepack enable
RUN npm install npm@latest -g
#RUN npm i && npm run build
RUN yarn install
RUN npm run valid
RUN npm start

