name: Update DataBase

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags' 
  push:
    branches: [ "main","release","develop" ]
    paths:
      - 'sql/flyway/sql/*.sql'
  pull_request:
    branches: [ "main","release","develop" ]
    paths:
      - 'sql/flyway/sql/*.sql'

jobs:
  flyway:
    name: Flyway
    runs-on: ubuntu-latest
    env:
      USER_DB: ${{ secrets.USER_DB }}
      PASSWORD_DB: ${{ secrets.PASSWORD_DB }}
      SCHEMA_DB: public
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Download and install Flyway
        run: |-
          wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/9.9.0/flyway-commandline-9.9.0-linux-x64.tar.gz | tar xz && sudo ln -s `pwd`/flyway-9.9.0/flyway /usr/local/bin 
          # tree .
          cd flyway-9.9.0/lib 
          wget https://jdbc.postgresql.org/download/postgresql-42.5.1.jar
          ls -lah
          cd ${GITHUB_WORKSPACE}/sql/flyway
          ls -lah
          bash myflyway.sh info prod
          bash myflyway.sh migrate prod
          bash myflyway.sh info prod

