name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  runscript:
    name: Example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Call a Bash Script
        run:  echo $(pwd) && ls -la ${GITHUB_WORKSPACE} && tree ${GITHUB_WORKSPACE}
