name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  runscript:
    name: Example
    runs-on: ubuntu-latest
    
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - 
        name: Call a Bash Script
        run:  echo $(pwd) && ls -la ${GITHUB_WORKSPACE} && tree ${GITHUB_WORKSPACE}
      - 
        name: Build with Maven Wrapper
        run: cd ${GITHUB_WORKSPACE}/alternative-courses && chmod +x mvnw && ./mvnw -B package --file pom.xml
      - 
        name: Qué paso con el código?
        run: cd ${GITHUB_WORKSPACE}/alternative-courses && ls -la && find -type f -iname "*.jar"
  runscript2:
    name: Example 2
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Checkout 2
        run: cd ${GITHUB_WORKSPACE}/alternative-courses && ls -la && find -type f -iname "*.jar" && echo "${{ secrets.PATO }}"
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: docker build
        run: cd ${GITHUB_WORKSPACE}/alternative-courses && docker build . -t tutum-demo:$(date +%s)


